version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URL=postgresql://user:password@db/library
      - MAX_CONTENT_LENGTH=10485760
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads:/app/uploads
    command: python run.py

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d library"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
  uploads:
